jobs:
  test:
      docker:
        - image: circleci/python:3.7-rc-node
      steps:
        - checkout
        - run:
            command: |
              sudo apt-get update; sudo apt-get install sqlite3 libsqlite3-dev libldap2-dev libsasl2-dev libssl-dev
              mkdir -p ./venv
              virtualenv ./venv
              . venv/bin/activate
              python setup.py check
              python setup.py install
              echo "*****************"
              echo "     PYTEST"
              echo "*****************"
              ./manage.py test -v3


workflows:
  version: 2
  test:
    jobs:
      - test