# Generated by Django 3.1.2 on 2020-10-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0008_alter_dataset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ngee_tropics_resources',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
