# Generated by Django 3.1.2 on 2021-01-14 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0009_alter_ngee_tropics_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^https?://orcid.org/[0-9]{4}-?[0-9]{4}-?[0-9]{4}-?([0-9]{4}|[0-9]{3}X)(/)*$', 'Enter a valid ORCiD (e.g. https://orcid.org/xxxx-xxxx-xxxx-xxxx)')]),
        ),
    ]
