# Generated by Django 3.1.2 on 2022-02-28 19:45

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0013_publication_workflow_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),

    ]
