# Generated by Django 3.1.2 on 2022-02-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0014_status_change_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='modified_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
