# Generated by Django 3.1.2 on 2022-03-03 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive_api', '0016_update_approval_publication_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataSet',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ngt_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='0.0', max_length=15)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Approved')], default=0)),
                ('status_comment', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('qaqc_status', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Provisional QA-QC'), (2, 'Full QA-QC')], null=True)),
                ('qaqc_method_description', models.TextField(blank=True, null=True)),
                ('ngee_tropics_resources', models.BooleanField(blank=True, null=True)),
                ('funding_organizations', models.TextField(blank=True, null=True)),
                ('doe_funding_contract_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledgement', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('additional_reference_information', models.TextField(blank=True, null=True)),
                ('originating_institution', models.TextField(blank=True, null=True)),
                ('access_level', models.IntegerField(choices=[(0, 'Private'), (1, 'NGEE Tropics'), (2, 'Public')], default=0)),
                ('additional_access_information', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True)),
                ('cdiac_import', models.BooleanField(default=False)),
                ('archive', models.TextField(max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=255, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cdiac_submission_contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='archive_api.person')),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='archive_api.person')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical data set',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
