# Generated by Django 3.1.2 on 2022-03-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0017_historicaldataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldataset',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
