# Generated by Django 3.1.14 on 2022-03-23 21:33

import archive_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0018_historical_change_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('service', models.IntegerField(choices=[(0, 'OSTI Elink'), (1, 'ESS-DIVE')], unique=True)),
                ('identity', models.CharField(blank=True, max_length=30, null=True)),
                ('secret', archive_api.models.SecretField(blank=True, editable=True, max_length=255, null=True)),
                ('endpoint', models.URLField(blank=False, null=False)),
            ],
        ),
    ]
