# Generated by Django 3.1.14 on 2022-04-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0020_dataset_doi_to_urlfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssDiveTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Metadata'), (1, 'Data')])),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'Queued'), (2, 'Running'), (3, 'Success'), (4, 'Failed'), (5, 'Retry')], default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archive_api.dataset')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
