# Generated by Django 3.1.14 on 2022-05-04 02:41

import archive_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0022_service_account_field_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='secret',
            field=archive_api.models.SecretField(blank=True, editable=True, max_length=2048, null=True),
        ),
    ]
