# Generated by Django 4.2.2 on 2024-02-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0027_add_dataset_desc_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldataset',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical data set', 'verbose_name_plural': 'historical data sets'},
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
