name: Lint Helm Charts

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.4.0

      - name: Helm Chart Testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: |
          CHANGED=`ct list-changed --config .github/lintconfig.yaml;`;
          LINTCONF=$CT_CONFIG_DIR/lintconf.yaml;
          for c in $CHANGED; do echo "$c/Chart.yaml"; yamllint  --config-file $LINTCONF  $c/Chart.yaml;  echo "$c/values.yaml"; yamllint  --config-file $LINTCONF  $c/values.yaml; done;