name: Deploy Pages
# Builds and deploys docs and helm charts

on:
  # Runs on publication of a release or prerelease
  release:
    types: [ released, prereleased ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python-dev-is-python3 libldap2-dev libsasl2-dev libssl-dev
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
      - name: Build with Charts
        # Outputs to the './_site' directory by default
        run: |
          helm dependency update helm
          helm package -d ./_site/charts helm
          helm repo index ./_site/charts
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build with Sphinx
        # Outputs to the './_site' directory by default
        run: |
          cd docs
          sphinx-build -b html -d ../_site/.doctrees   . ../_site
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
